microservice-chart:
  image:
    repository: cstardcommonacr.azurecr.io/idpayadmissibilityassessor
    tag: latest
    pullPolicy: Always

  ingress:
    host: "dev01.idpay.internal.dev.cstar.pagopa.it"

  resources:
    requests:
      memory: "768Mi"
      cpu: "150m"
    limits:
      memory: "768Mi"
      cpu: "600m"

  autoscaling:
    enable: true
    minReplica: 1
    maxReplica: 2
    pollingInterval: 30 # seconds
    cooldownPeriod: 300 # seconds
    triggers:
      - type: cpu
        metadata:
          type: Utilization # Allowed types are 'Utilization' or 'AverageValue'
          value: "70"

  envSecret:
    aks-api-url: cstar-d-weu-dev01-aks-apiserver-url
    PAGOPA_PDND_CONFIGURATION_JWT_KEY_C001: pagopa-pdnd-configuration-jwt-key-c001
    PAGOPA_PDND_CONFIGURATION_AGID_JWT_PUB_C001: pagopa-pdnd-configuration-agid-jwt-pub-c001
    PAGOPA_PDND_CONFIGURATION_CLIENT_ID_C001: pagopa-pdnd-configuration-client-id-c001
    PAGOPA_PDND_CONFIGURATION_KID_C001: pagopa-pdnd-configuration-kid-c001
    PAGOPA_PDND_CONFIGURATION_PURPOSE_ID_C001: pagopa-pdnd-configuration-purpose-id-c001
    PAGOPA_PDND_CONFIGURATION_JWT_KEY_C021: pagopa-pdnd-configuration-jwt-key-c021
    PAGOPA_PDND_CONFIGURATION_AGID_JWT_PUB_C021: pagopa-pdnd-configuration-agid-jwt-pub-c021
    PAGOPA_PDND_CONFIGURATION_CLIENT_ID_C021: pagopa-pdnd-configuration-client-id-c021
    PAGOPA_PDND_CONFIGURATION_KID_C021: pagopa-pdnd-configuration-kid-c021
    PAGOPA_PDND_CONFIGURATION_PURPOSE_ID_C021: pagopa-pdnd-configuration-purpose-id-c021

  keyvault:
    name: "cstar-d-idpay-kv"
    tenantId: "7788edaf-0346-4068-9d79-c868aed15b3d"

  envConfig:
    JAVA_TOOL_OPTIONS: "-Xms256m -Xmx512m -Djava.util.concurrent.ForkJoinPool.common.parallelism=7 -Dio.netty.eventLoopThreads=100 -javaagent:/app/applicationinsights-agent.jar -Dapplicationinsights.configuration.file=/mnt/file-config-external/appinsights-config/applicationinsights.json -agentlib:jdwp=transport=dt_socket,server=y,address=8001,suspend=n -Dcom.sun.management.jmxremote=true -Dcom.sun.management.jmxremote.port=3002 -Dcom.sun.management.jmxremote.rmi.port=3003 -Djava.rmi.server.hostname=127.0.0.1 -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false"
    CACHE_REFRESH_MS_RATE: "60000"
    REDIS_CACHE_ENABLED: "true"

    #PDND_BASE_URL: http://idpay-mock-microservice-chart:8080/idpay/mock/pdnd
    PDND_ACCESS_TOKEN_AUDIENCE: auth.uat.interop.pagopa.it/client-assertion

    ANPR_ENV: dev
    ANPR_AUTH_USERID: pagopa-idpay
    #ANPR_BASE_URL: http://idpay-mock-microservice-chart:8080/idpay/mock/anpr
    ANPR_BASE_URL: https://modipa-val.anpr.interno.it/govway/rest/in/MinInternoPortaANPR-PDND

    INPS_ISEE_CONSULTATION_BASE_URL: http://idpay-mock-microservice-chart:8080/idpay/mock/inps/soap
